version: '3'

services:
    db:
        image: 'mongo:latest'
        ports:
            - '27017:27017'
    api:
        build: .
        restart: always
        command: sh -c "yarn install && yarn run dev"
        volumes:
            - .:/src
        ports:
            - "3000:3000"
        environment:
            PORT: 3000
        depends_on:
            - db
